name: Deployment pipeline
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: recettesrodrigo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up database
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: recettesrodrigo
          DB_USER: postgres
          PGPASSWORD: postgres
        run: |
          psql -h $DB_HOST -U $DB_USER -d $DB_DATABASE -f ./database/03_recettesrodrigo_ddl.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_DATABASE -f ./database/04_insert_donnees.sql

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: recettesrodrigo
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: npm run test

      - name: Start backend
        working-directory: ./backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: recettesrodrigo
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: npm run start

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test

      - name: Build frontend application
        working-directory: ./frontend
        run: npm run build