name: Deploy to Vercel

on:
  workflow_run:
    workflows: [ "Backend Deployment", "Frontend Deployment", "End-to-End Tests" ]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to Vercel
        # run: curl -X POST https://api.vercel.com/v1/integrations/deploy/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        run: echo "Déploiement effectué. (À faire)"

      - name: Deploy frontend to Vercel
        # run: curl -X POST https://api.vercel.com/v1/integrations/deploy/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        run: echo "Déploiement effectué. (À faire)"