name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  backend_validation:
    uses: cmurphy-cegep/projet-integrateur-deiber-ionut-romain/.github/workflows/backend_validation.yml@main

  frontend_validation:
    uses: cmurphy-cegep/projet-integrateur-deiber-ionut-romain/.github/workflows/frontend_validation.yml@main

  end_to_end_tests:
    uses: cmurphy-cegep/projet-integrateur-deiber-ionut-romain/.github/workflows/end_to_end_tests.yml@main

  deploy_to_vercel:
    runs-on: ubuntu-latest

    needs: [ backend_validation, frontend_validation, end_to_end_tests ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to Vercel
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_g0ehkF5dpb7xoaZ4ZbtzzmvBk2Xd/BTRD4kq7xk

      - name: Deploy frontend to Vercel
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_zNmNyfdqrPcxWUoN2ARzwSKfiYLo/qrF1UgWsFh

      - name: Lien site web
        run: echo "https://projet-integrateur-deiber-ionut-romain.vercel.app"