name: End-to-End Tests
on:
  push:
    branches-ignore:
      - main
  #    paths:
  #      - 'backend/**'
  #      - 'frontend/**'  # Déclenche si des fichiers du backend ou du frontend sont modifiés

  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: recettesrodrigo
      DB_USER: postgres
      DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_DATABASE }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up database
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}
        run: |
          psql -h $DB_HOST -U $DB_USER -d $DB_DATABASE -f ./database/03_recettesrodrigo_ddl.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_DATABASE -f ./database/04_insert_donnees.sql

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend
        working-directory: ./backend
        run: npm run start &

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          until curl -s http://localhost:3000/health; do sleep 5; done

      - name: Run end-to-end tests
        working-directory: ./frontend
        env:
          PATH: ${{ runner.tool_cache }}/geckodriver:$PATH
        run: |
          # Set up GeckoDriver for Firefox
          npm install geckodriver --save-dev
          export PATH=$(npm bin):$PATH
          npm run test