name: Block Main Pushes

on:
  push:
    branches:
      - main

jobs:
  block_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail to block direct push to main
        run: |
          echo "Direct pushes to the main branch are not allowed. Please create a pull request."
          exit 1